export const AppStrings = {
  APP_NAME: 'GRAVITINO AZD API',
  APP_DESCRIPTION: 'Автоматизация закупочной деятельности',
  APP_VERSION: '1.0',

  ASC: 'ASC',

  AUTH_LOGIN_OPERATION: 'Авторизация пользователя',
  AUTH_LOGOUT_OPERATION: 'Выход из аккаунта',

  ORGANIZATION_CREATED_RESPONSE: 'Организация создана',
  ORGANIZATION_CREATE_OPERATION: 'Создание организации',
  ORGANIZATION_ALL_RESPONSE: 'Список организаций получен',
  ORGANIZATION_ALL_OPERATION: 'Получение списка всех организаций',
  ORGANIZATION_MY_RESPONSE: 'Список организаций пользователя получен',
  ORGANIZATION_MY_OPERATION: 'Получение списка всех организаций пользователя',
  ORGANIZATION_ALL_BY_CHECKPOINT_RESPONSE: 'Список организаций получен',
  ORGANIZATION_ALL_BY_CHECKPOINT_OPERATION: 'Получение списка всех организаций по пункту пропуска',
  ORGANIZATION_UPDATE_RESPONSE: 'Организация изменена',
  ORGANIZATION_UPDATE_OPERATION: 'Изменение организации',
  ORGANIZATION_DELETE_RESPONSE: 'Организация удалена',
  ORGANIZATION_DELETE_OPERATION: 'Удаление организации',
  ORGANIZATION_IMPORT_RESPONSE: 'Организации импортированы',
  ORGANIZATION_IMPORT_OPERATION: 'Импорт организаций',
  ORGANIZATION_IMPORT_UPLOAD_RESPONSE: 'Файл импорта загружен',
  ORGANIZATION_IMPORT_UPLOAD_OPERATION: 'Предпросмотр импорта организаций',

  ORGANIZATION_TYPE_ALL_RESPONSE: 'Список типов организаций получен',
  ORGANIZATION_TYPE_ALL_OPERATION: 'Получение списка всех типов организаций',

  PERMISSION_CREATE_RESPONSE: 'Разрешение создано',
  PERMISSION_CREATE_OPERATION: 'Создание разрешения',
  PERMISSION_ALL_RESPONSE: 'Список разрешений получен',
  PERMISSION_ALL_OPERATION: 'Получение списка всех разрешений',
  PERMISSION_UPDATE_RESPONSE: 'Разрешение изменено',
  PERMISSION_UPDATE_OPERATION: 'Изменение разрешения',
  PERMISSION_DELETE_RESPONSE: 'Разрешение удалено',
  PERMISSION_DELETE_OPERATION: 'Удаление разрешения',

  PLAN_CREATE_RESPONSE: 'План-график создан',
  PLAN_CREATE_OPERATION: 'Создание плана-графика',
  PLAN_ALL_RESPONSE: 'Список планов-графиков получен',
  PLAN_ALL_OPERATION: 'Получение списка всех планов-графиков',
  PLAN_UPDATE_RESPONSE: 'План-график изменен',
  PLAN_UPDATE_OPERATION: 'Изменение плана-графика',
  PLAN_DELETE_RESPONSE: 'План-график удалено',
  PLAN_DELETE_OPERATION: 'Удаление плана-графика',

  PLAN_WAY_ALL_RESPONSE: 'Список способов получен',
  PLAN_WAY_ALL_OPERATION: 'Получение списка всех способов',

  PROPERTY_CREATE_RESPONSE: 'Характеристика создана',
  PROPERTY_CREATE_OPERATION: 'Создание характеристики',
  PROPERTY_ALL_RESPONSE: 'Список характеристик получен',
  PROPERTY_ALL_OPERATION: 'Получение списка всех характеристик',
  PROPERTY_UPDATE_RESPONSE: 'Характеристика изменена',
  PROPERTY_UPDATE_OPERATION: 'Изменение характеристики',
  PROPERTY_DELETE_RESPONSE: 'Характеристика удалена',
  PROPERTY_DELETE_OPERATION: 'Удаление характеристики',

  ROLE_CREATE_RESPONSE: 'Роль создана',
  ROLE_CREATE_OPERATION: 'Создание роли',
  ROLE_ALL_RESPONSE: 'Список ролей получен',
  ROLE_ALL_OPERATION: 'Получение списка всех ролей',
  ROLE_UPDATE_RESPONSE: 'Роль изменена',
  ROLE_UPDATE_OPERATION: 'Изменение роли',
  ROLE_DELETE_RESPONSE: 'Роль удалена',
  ROLE_DELETE_OPERATION: 'Удаление роли',

  ROLE_PERMISSION_CREATED_RESPONSE: 'Разрешение добавлено',
  ROLE_PERMISSION_CREATE_OPERATION: 'Добавление разрешения',
  ROLE_PERMISSIONS_CREATED_RESPONSE: 'Разрешения добавлены',
  ROLE_PERMISSIONS_CREATE_OPERATION: 'Добавление разрешений',
  ROLE_PERMISSION_ALL_RESPONSE: 'Список разрешений получен',
  ROLE_PERMISSION_ALL_OPERATION: 'Получение списка всех разрешений',
  ROLE_PERMISSION_MY_RESPONSE: 'Список разрешений пользователя получен',
  ROLE_PERMISSION_MY_OPERATION: 'Получение списка всех разрешений пользователя',
  ROLE_PERMISSION_UPDATE_RESPONSE: 'Разрешение изменено',
  ROLE_PERMISSION_UPDATE_OPERATION: 'Изменение разрешения',
  ROLE_PERMISSION_DELETE_RESPONSE: 'Разрешение удалено',
  ROLE_PERMISSION_DELETE_OPERATION: 'Удаление разрешения',

  USERS_CREATE_OPERATION: 'Регистрация пользователя',
  USERS_CREATE_RESPONSE: 'Пользователь успешно зарегистрирован',
  USERS_CHECK_EXISTS_OPERATION: 'Проверка существования пользователя',
  USERS_CHECK_EXISTS_RESPONSE: 'Пользователь (не)зарегистрирован',
  USERS_GET_CURRENT_OPERATION: 'Получение данных текущего пользователя',
  USERS_GET_CURRENT_RESPONSE: 'Данные успешно получены',
  USERS_UPDATE_CURRENT_OPERATION: 'Изменение данных текущего пользователя',
  USERS_UPDATE_CURRENT_RESPONSE: 'Данные успешно изменены',
  USERS_UPDATE_PASSWORD_OPERATION: 'Изменение пароля текущего пользователя',
  USERS_UPDATE_PASSWORD_RESPONSE: 'Пароль успешно изменен',
  USERS_RESET_PASSWORD_OPERATION: 'Сброс пароля текущего пользователя',
  USERS_RESET_PASSWORD_RESPONSE: 'Пароль успешно изменен',
  USERS_DELETE_CURRENT_OPERATION: 'Удаление текущего пользователя',
  USERS_DELETE_CURRENT_RESPONSE: 'Пользователь успешно удален',
}
