export const AppStrings = {
  APP_NAME: 'GRAVITINO AZD API',
  APP_DESCRIPTION: 'Автоматизация закупочной деятельности',
  APP_VERSION: '1.0',

  ASC: 'ASC',

  PROPERTY_VALUES: 'Дополнительные характеристики',

  BRANCH_CREATED_RESPONSE: 'Филиал создан',
  BRANCH_CREATE_OPERATION: 'Создание филиала',
  BRANCH_ALL_RESPONSE: 'Список филиалов получен',
  BRANCH_ALL_OPERATION: 'Получение списка всех филиалов',
  BRANCH_UPDATE_RESPONSE: 'Филиал изменен',
  BRANCH_UPDATE_OPERATION: 'Изменение филиала',
  BRANCH_DELETE_RESPONSE: 'Филиал удален',
  BRANCH_DELETE_OPERATION: 'Удаление филиала',

  CURRENCY_ALL_RESPONSE: 'Список валют получен',
  CURRENCY_ALL_OPERATION: 'Получение списка всех валют',

  KOSGU_ALL_RESPONSE: 'КОСГУ получены',
  KOSGU_ALL_OPERATION: 'Получение списка кодов КОСГУ',

  LIMIT_CREATE_RESPONSE: 'Лимит создан',
  LIMIT_CREATE_OPERATION: 'Создание лимита',
  LIMIT_ALL_RESPONSE: 'Список лимитов получен',
  LIMIT_ALL_OPERATION: 'Получение списка всех лимитов',
  LIMIT_ONE_RESPONSE: 'Лимит получен',
  LIMIT_ONE_OPERATION: 'Получение лимита по UUID',
  LIMIT_UPDATE_RESPONSE: 'Лимит изменен',
  LIMIT_UPDATE_OPERATION: 'Изменение лимита',
  LIMIT_DELETE_RESPONSE: 'Лимит удален',
  LIMIT_DELETE_OPERATION: 'Удаление лимита',

  LIMIT_EVENT_ALL_RESPONSE: 'Список событий лимита получен',
  LIMIT_EVENT_ALL_OPERATION: 'Получение списка всех событий лимита',

  LIMIT_STATUS_ALL_RESPONSE: 'Список статусов лимитов получен',
  LIMIT_STATUS_ALL_OPERATION: 'Получение списка всех статусов лимитов',

  ORGANIZATION_CREATED_RESPONSE: 'Организация создана',
  ORGANIZATION_CREATE_OPERATION: 'Создание организации',
  ORGANIZATION_ALL_RESPONSE: 'Список организаций получен',
  ORGANIZATION_ALL_OPERATION: 'Получение списка всех организаций',
  ORGANIZATION_UPDATE_RESPONSE: 'Организация изменена',
  ORGANIZATION_UPDATE_OPERATION: 'Изменение организации',
  ORGANIZATION_DELETE_RESPONSE: 'Организация удалена',
  ORGANIZATION_DELETE_OPERATION: 'Удаление организации',

  ORGANIZATION_TYPE_ALL_RESPONSE: 'Список типов организаций получен',
  ORGANIZATION_TYPE_ALL_OPERATION: 'Получение списка всех типов организаций',

  PERMISSION_CREATE_RESPONSE: 'Разрешение создано',
  PERMISSION_CREATE_OPERATION: 'Создание разрешения',
  PERMISSION_ALL_RESPONSE: 'Список разрешений получен',
  PERMISSION_ALL_OPERATION: 'Получение списка всех разрешений',
  PERMISSION_UPDATE_RESPONSE: 'Разрешение изменено',
  PERMISSION_UPDATE_OPERATION: 'Изменение разрешения',
  PERMISSION_DELETE_RESPONSE: 'Разрешение удалено',
  PERMISSION_DELETE_OPERATION: 'Удаление разрешения',

  PERSON_ALL_OPERATION: 'Получение списка всех данных пользователей',
  PERSON_ALL_RESPONSE: 'Список данных получен',

  PLAN_CREATE_RESPONSE: 'План-график создан',
  PLAN_CREATE_OPERATION: 'Создание плана-графика',
  PLAN_ALL_RESPONSE: 'Список планов-графиков получен',
  PLAN_ALL_OPERATION: 'Получение списка всех планов-графиков',
  PLAN_ONE_RESPONSE: 'План-график получен',
  PLAN_ONE_OPERATION: 'Получение плана-графика по UUID',
  PLAN_UPDATE_RESPONSE: 'План-график изменен',
  PLAN_UPDATE_OPERATION: 'Изменение плана-графика',
  PLAN_DELETE_RESPONSE: 'План-график удалено',
  PLAN_DELETE_OPERATION: 'Удаление плана-графика',

  PLAN_POSITION_CREATE_RESPONSE: 'Позиция плана-графика создана',
  PLAN_POSITION_CREATE_OPERATION: 'Создание позиции плана-графика',
  PLAN_POSITION_ALL_RESPONSE: 'Список позиций плана-графика получен',
  PLAN_POSITION_ALL_OPERATION: 'Получение списка всех позиций плана-графика',
  PLAN_POSITION_ONE_RESPONSE: 'Позиция плана-графика получена',
  PLAN_POSITION_ONE_OPERATION: 'Получение позиции плана-графика по UUID',
  PLAN_POSITION_UPDATE_RESPONSE: 'Позиция плана-графика изменена',
  PLAN_POSITION_UPDATE_OPERATION: 'Изменение позиции плана-графика',
  PLAN_POSITION_DELETE_RESPONSE: 'Позиция плана-графика удалена',
  PLAN_POSITION_DELETE_OPERATION: 'Удаление позиции плана-графика',

  PLAN_EVENT_ALL_RESPONSE: 'Список событий плана-графика получен',
  PLAN_EVENT_ALL_OPERATION: 'Получение списка всех событий планов-графиков',

  PLAN_STATUS_ALL_RESPONSE: 'Список статусов планов получен',
  PLAN_STATUS_ALL_OPERATION: 'Получение списка всех статусов планов',

  PLAN_WAY_ALL_RESPONSE: 'Список способов получен',
  PLAN_WAY_ALL_OPERATION: 'Получение списка всех способов',

  PROPERTY_CREATE_RESPONSE: 'Характеристика создана',
  PROPERTY_CREATE_OPERATION: 'Создание характеристики',
  PROPERTY_ALL_RESPONSE: 'Список характеристик получен',
  PROPERTY_ALL_OPERATION: 'Получение списка всех характеристик',
  PROPERTY_UPDATE_RESPONSE: 'Характеристика изменена',
  PROPERTY_UPDATE_OPERATION: 'Изменение характеристики',
  PROPERTY_DELETE_RESPONSE: 'Характеристика удалена',
  PROPERTY_DELETE_OPERATION: 'Удаление характеристики',

  PURCHASE_CREATE_RESPONSE: 'Закупка создана',
  PURCHASE_CREATE_OPERATION: 'Создание закупки',
  PURCHASE_ALL_RESPONSE: 'Список закупок получен',
  PURCHASE_ALL_OPERATION: 'Получение списка всех закупок',
  PURCHASE_ONE_RESPONSE: 'Закупка получена',
  PURCHASE_ONE_OPERATION: 'Получение закупки по UUID',
  PURCHASE_UPDATE_RESPONSE: 'Закупка изменена',
  PURCHASE_UPDATE_OPERATION: 'Изменение закупки',
  PURCHASE_DELETE_RESPONSE: 'Закупка удалена',
  PURCHASE_DELETE_OPERATION: 'Удаление закупки',

  PURCHASE_EVENT_ALL_RESPONSE: 'Список событий закупки получен',
  PURCHASE_EVENT_ALL_OPERATION: 'Получение списка всех событий закупки',

  PURCHASE_STEP_ALL_RESPONSE: 'Список этапов закупок получен',
  PURCHASE_STEP_ALL_OPERATION: 'Получение списка всех этапов закупок',

  PURCHASE_TYPE_ALL_RESPONSE: 'Список типов закупок получен',
  PURCHASE_TYPE_ALL_OPERATION: 'Получение списка всех типов закупок',

  ROLE_CREATE_RESPONSE: 'Роль создана',
  ROLE_CREATE_OPERATION: 'Создание роли',
  ROLE_ALL_RESPONSE: 'Список ролей получен',
  ROLE_ALL_OPERATION: 'Получение списка всех ролей',
  ROLE_UPDATE_RESPONSE: 'Роль изменена',
  ROLE_UPDATE_OPERATION: 'Изменение роли',
  ROLE_DELETE_RESPONSE: 'Роль удалена',
  ROLE_DELETE_OPERATION: 'Удаление роли',

  ROLE_PERMISSION_CREATED_RESPONSE: 'Разрешение добавлено',
  ROLE_PERMISSION_CREATE_OPERATION: 'Добавление разрешения',
  ROLE_PERMISSIONS_CREATED_RESPONSE: 'Разрешения добавлены',
  ROLE_PERMISSIONS_CREATE_OPERATION: 'Добавление разрешений',
  ROLE_PERMISSION_ALL_RESPONSE: 'Список разрешений получен',
  ROLE_PERMISSION_ALL_OPERATION: 'Получение списка всех разрешений',
  ROLE_PERMISSION_MY_RESPONSE: 'Список разрешений пользователя получен',
  ROLE_PERMISSION_MY_OPERATION: 'Получение списка всех разрешений пользователя',
  ROLE_PERMISSION_UPDATE_RESPONSE: 'Разрешение изменено',
  ROLE_PERMISSION_UPDATE_OPERATION: 'Изменение разрешения',
  ROLE_PERMISSIONS_UPDATE_RESPONSE: 'Разрешения изменены',
  ROLE_PERMISSIONS_UPDATE_OPERATION: 'Изменение разрешений у роли или пользователя',
  ROLE_PERMISSION_DELETE_RESPONSE: 'Разрешение удалено',
  ROLE_PERMISSION_DELETE_OPERATION: 'Удаление разрешения',

  TECHNICAL_TASK_CREATE_RESPONSE: 'Техническое задание создано',
  TECHNICAL_TASK_CREATE_OPERATION: 'Создание технического задания',
  TECHNICAL_TASK_ALL_RESPONSE: 'Список технических заданий получен',
  TECHNICAL_TASK_ALL_OPERATION: 'Получение списка всех технических заданий',
  TECHNICAL_TASK_PURCHASE_RESPONSE: 'Технические задания закупки получены',
  TECHNICAL_TASK_PURCHASE_OPERATION: 'Получение списка всех технических заданий закупки',
  TECHNICAL_TASK_UPDATE_RESPONSE: 'Техническое задание изменено',
  TECHNICAL_TASK_UPDATE_OPERATION: 'Изменение технического задания',
  TECHNICAL_TASK_DELETE_RESPONSE: 'Техническое задание удалено',
  TECHNICAL_TASK_DELETE_OPERATION: 'Удаление технического задания',

  USERS_CREATE_OPERATION: 'Регистрация пользователя',
  USERS_CREATE_RESPONSE: 'Пользователь успешно зарегистрирован',
  USERS_CHECK_EXISTS_OPERATION: 'Проверка существования пользователя',
  USERS_CHECK_EXISTS_RESPONSE: 'Пользователь (не)зарегистрирован',
  USERS_GET_CURRENT_OPERATION: 'Получение данных текущего пользователя',
  USERS_GET_CURRENT_RESPONSE: 'Данные успешно получены',
  USERS_ALL_OPERATION: 'Получение списка всех пользователей',
  USERS_ALL_RESPONSE: 'Пользователи успешно получены',
  USERS_UPDATE_CURRENT_OPERATION: 'Изменение данных текущего пользователя',
  USERS_UPDATE_CURRENT_RESPONSE: 'Данные успешно изменены',
  USERS_UPDATE_PASSWORD_OPERATION: 'Изменение пароля текущего пользователя',
  USERS_UPDATE_PASSWORD_RESPONSE: 'Пароль успешно изменен',
  USERS_RESET_PASSWORD_OPERATION: 'Сброс пароля текущего пользователя',
  USERS_UPDATE_STATUS_OPERATION: 'Изменение статуса текущего пользователя',
  USERS_UPDATE_STATUS_RESPONSE: 'Статус успешно изменен',
  USERS_RESET_PASSWORD_RESPONSE: 'Пароль успешно изменен',
  USERS_DELETE_CURRENT_OPERATION: 'Удаление текущего пользователя',
  USERS_DELETE_CURRENT_RESPONSE: 'Пользователь успешно удален',

  PLAN_PURCHASE_NAME: 'Наименование закупки',
  PLAN_PURCHASE_PRICE: 'Стоимость закупки',
  PLAN_PURCHASE_DATE: 'Дата закупки',
  PLAN_PURCHASE_UUID: 'UUID закупки',
  PLAN_STATUS: 'Статус плана',
  PLAN_KOSGU: 'КОСГУ',
  PLAN_OFFER_NUMBER: 'Номер предложения на закупку (Электронный бюджет)',
  PLAN_OKPD2: 'Код ОКПД2',
  PLAN_OBJECT_NAME: 'Наименование объекта закупки',
  PLAN_OKEI: 'Код по ОКЕИ',
  PLAN_RESULT_NAME: 'Наименование результата закупки товара, работ, услуги',
  PLAN_NPA_DATE:
    'Дата / Сведения о НПА, утвержденных в соответствии со ст. 19 Федерального закона от 05.04.2013 № 44-ФЗ',
  PLAN_NPA_NUMBER:
    'Номер, Вид документа / Сведения о НПА, утвержденных в соответствии со ст. 19 Федерального закона от 05.04.2013 № 44-ФЗ',
  PLAN_CURRENT_YEAR_COUNT: 'Плановое значение. Кол-во. Текущий год.',
  PLAN_CURRENT_YEAR_PRICE: 'Плановое значение. Средняя цена. Текущий год.',
  PLAN_FIRST_YEAR_COUNT: 'Плановое значение. Кол-во. Следующий год.',
  PLAN_FIRST_YEAR_PRICE: 'Плановое значение. Средняя цена. Следующий год.',
  PLAN_SECOND_YEAR_COUNT: 'Плановое значение. Кол-во. Второй год.',
  PLAN_SECOND_YEAR_PRICE: 'Плановое значение. Средняя цена. Второй год.',
  PLAN_NEXT_YEAR_COUNT: 'Плановое значение. Кол-во. Последующие года.',
  PLAN_NEXT_YEAR_PRICE: 'Плановое значение. Средняя цена. Последующие года.',
  PLAN_CURRENT_YEAR_LIMIT: 'Объем финансового обеспечения. Текущий год.',
  PLAN_FIRST_YEAR_LIMIT: 'Объем финансового обеспечения. Следующий год.',
  PLAN_SECOND_YEAR_LIMIT: 'Объем финансового обеспечения. Второй год.',
  PLAN_NEXT_YEAR_LIMIT: 'Объем финансового обеспечения. Последующие года.',
  PLAN_START_MAX_PRICE: 'Начальная (максимальная) цена контракта.',
  PLAN_PUBLIC_PURCHASE_DISCUSSION:
    'Информация о проведении обязательного общественного обсуждения закупки',
  PLAN_AUTHORIZED_INSTITUTION: 'Наименование уполномоченного органа (учреждения)',
  PLAN_ORGANIZER_NAME: 'Наименование организатора проведения совместного конкурса или аукциона',
  PLAN_PLACEMENT_MONTH: 'Месяц размещения извещения или заключения контракта у ед. поставщика',
  PLAN_WAY_ID: 'ID Способа',
  PLAN_WAY: 'Способ',
  PLAN_SMALL_BUSINESS: 'Осуществление закупки у СМП и СОНО',
  PLAN_INITIATOR: 'Инициатор',
  PLAN_BRANCH_UUID: 'UUID филиала',
  PLAN_BRANCH: 'Филиал',
  PLAN_PRICE_VALUE:
    'Заключено государственных контрактов, договоров, закуплено продукции на сумму, не превышающую шестисот тысяч рублей. В стоимостном выражении (руб.)',
  PLAN_SAVINGS:
    'Заключено государственных контрактов, договоров, закуплено продукции на сумму, не превышающую шестисот тысяч рублей. Экономия по результатам размещения заказа (руб.)',
  PLAN_CONTRACT_NUMBER: '№ Контракта',
  PLAN_CONTRACT_DATE: 'Дата Контракта',
  PLAN_CONTRAGENT: 'Контрагент',
  PLAN_APPROVAL_LETTER: 'Письмо согласования/ письмо уведомления (номер и дата)',
}
